### ISSUE TITLE
Consertar erro na conversão

### ISSUE THREAD

**Issue by frattezi** [anacaldasm/segundo-ciclo-de-mentoria#1]
Hoje, quando tento realizar a conversão de um valor entre duas moedas pela aplicação não obtenho resultado.

**Erro demonstrado**:
```json
index.js:46 Uncaught TypeError: Cannot read property 'value' of null
    at onClickConverter (index.js:46)
    at HTMLButtonElement.onclick (index.html:41)
```

**Aceite**:
- Corrigir o erro no código javascript.
- Ser possível realizar a conversão para valores válidos com as moedas suportadas.

**Comment by anacaldasm** [comment]
pull request https://github.com/anacaldasm/conversor-de-moeda/pull/1
