### ISSUE TITLE
Criar novo header da aplicação

### ISSUE THREAD

**Issue by frattezi** [anacaldasm/segundo-ciclo-de-mentoria#2]
Na aplicação já existente, criar um header utilizando o bootstrap para estilos e icones.

![header](https://user-images.githubusercontent.com/14007745/103822308-a45a8900-504e-11eb-9f63-48862bc5ade8.png)

[Link para mockup](https://www.figma.com/file/zIRtaQyraOvRmsssLR8wBe/Bootstrap-UI-Kit-Community?node-id=2%3A567)

**Aceite**
- Header feito como na descrição utilizando bootstrap para fonte
- Icone bootstrap
- Posicionamento correto dos elementos

**Comment by anacaldasm** [comment]
https://icons.getbootstrap.com/icons/wallet2/

**Comment by anacaldasm** [comment]
https://github.com/anacaldasm/conversor-de-moeda/pull/2 @frattezi
