### ISSUE TITLE
Adicionar exercício fatorial ao podcodar/exercises

### ISSUE THREAD

**Issue by frattezi** [anacaldasm/segundo-ciclo-de-mentoria#8]
E NÃO É SÓ ISSO, O GERENTE FICOU DOIDO.

Como você já resolveu o exercício em grupo, você vai:
- Adicionar o exercício no repo da PodCodar, aqui você vai apenas
  - Adicionar a ordem do exercício como um readme, baseado no SPOJ
  - Adicionar arquivo base e arquivo de testes 
- Atualizar seu repositório com o exercício
- Resolver o danadinho!

Vale usar lib, oque quiser, desde que consiga. MUhUAMUahmUAH(risada maléfica)
{\__/}
(●_●)
( >🌮 Want a taco?
https://www.urionlinejudge.com.br/judge/pt/problems/view/1161

**Comment by anacaldasm** [comment]
https://github.com/podcodar/exercises/pull/25#issue-560705915
